/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#include "Game.h"

#ifndef _Included_com_example_jligameenginetest_JLIGameEngineTestLib
#define _Included_com_example_jligameenginetest_JLIGameEngineTestLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jligameenginetest_JLIGameEngineTestLib
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_jligameenginetest_JLIGameEngineTestLib_create
  (JNIEnv *env, jclass cls)
{
	create();
}

/*
 * Class:     com_example_jligameenginetest_JLIGameEngineTestLib
 * Method:    resize
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_example_jligameenginetest_JLIGameEngineTestLib_resize
  (JNIEnv *env, jclass cls, jint x, jint y, jint width, jint height)
{
	resize(x, y, width, height);
}

/*
 * Class:     com_example_jligameenginetest_JLIGameEngineTestLib
 * Method:    update
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_example_jligameenginetest_JLIGameEngineTestLib_update
  (JNIEnv *env, jclass cls, jfloat step)
{
	update(step);
}

/*
 * Class:     com_example_jligameenginetest_JLIGameEngineTestLib
 * Method:    render
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_jligameenginetest_JLIGameEngineTestLib_render
  (JNIEnv *env, jclass cls)
{
	render();
}

/*
 * Class:     com_example_jligameenginetest_JLIGameEngineTestLib
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_jligameenginetest_JLIGameEngineTestLib_destroy
  (JNIEnv *env, jclass cls)
{
	destroy();
}

/*
 * Class:     com_example_jligameenginetest_JLIGameEngineTestLib
 * Method:    pause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_jligameenginetest_JLIGameEngineTestLib_pause
  (JNIEnv *env, jclass cls)
{
	pause();
}

/*
 * Class:     com_example_jligameenginetest_JLIGameEngineTestLib
 * Method:    unpause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_jligameenginetest_JLIGameEngineTestLib_unpause
  (JNIEnv *env, jclass cls)
{
	unpause();
}

#ifdef __cplusplus
}
#endif
#endif
